name: Build and Deploy Java Web Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: 52.38.254.59
      EC2_DESTINATION_PATH: /usr/local/tomcat/webapps

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -X

      - name: Display Maven Output
        run: cat target/build.log

      - name: Upload WAR file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          source: target/javawebapplication-*.war
          target: ${{ env.EC2_DESTINATION_PATH }}
