name: Build and Deploy Java Web Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    #env:
     # EC2_HOST: 52.38.254.59
     # EC2_DESTINATION_PATH: /usr/local/tomcat/webapps

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -X

      - name: List files in target directory
        run: ls -R target

      - name: Upload WAR file to EC2
        run: |
          scp -o StrictHostKeyChecking=no -o PasswordAuthentication=yes target/spring-boot-hello-world-example-0.0.1-SNAPSHOT.war testuser@52.38.254.59:/usr/local/tomcat/webapps
          echo test1
          
