name: Build and Deploy Java Web Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: 54.244.205.137
      EC2_DESTINATION_PATH: /usr/local/tomcat/webapps

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Take Backup of Existing WAR
        uses: appleboy/ssh-action@v0.7.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            sudo cp /usr/local/tomcat/webapps/javawebapplication.war /usr/local/tomcat/backup/javawebapplication.war.backup

      - name: Build with Maven
        run: mvn clean install -X

      - name: Display Maven Output
        run: cat target/build.log

      - name: Upload WAR file to EC2
        uses: appleboy/scp-action@v0.1.4pls nevve chesuko
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          source: target/javawebapplication-*.war
          target: ${{ env.EC2_DESTINATION_PATH }}
		  
	  - name: Restart Tomcat
		uses: appleboy/ssh-action@v0.7.0
		with:
		  host: ${{ env.EC2_HOST }}
		  username: ${{ secrets.EC2_USERNAME }}
		  password: ${{ secrets.EC2_PASSWORD }}
		  script: |
		  sudo /etc/init.d/tomcat restart

  provide-download-link:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v3
        with:
          name: javawebapplication
          path: target/

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Generate Download Link
        run: |
          echo "Download the built WAR file [here](https://github.com/${{ github.repository }}/raw/${{ github.sha }}/target/javawebapplication-*.war)"
