name: Build and Deploy Java Web Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: 52.33.211.237
      EC2_DESTINATION_PATH: /usr/local/tomcat/webapps
      BACKUP_PATH: /usr/local/tomcat/backup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -X

      - name: List files in target directory
        run: ls -R target

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Take backup of existing WAR file
        run: |
          TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
          sshpass -p ${{ secrets.EC2_PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USERNAME }}@${{ env.EC2_HOST }} "mv ${{ env.EC2_DESTINATION_PATH }}/spring-boot-hello-world-example-0.0.1-SNAPSHOT.war ${{ env.BACKUP_PATH }}/spring-boot-hello-world-example-0.0.1-SNAPSHOT_backup_${TIMESTAMP}.war"

      - name: Upload WAR file to EC2
        run: sshpass -p ${{ secrets.EC2_PASSWORD }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r target/spring-boot-hello-world-example-0.0.1-SNAPSHOT.war ${{ secrets.EC2_USERNAME }}@${{ env.EC2_HOST }}:${{ env.EC2_DESTINATION_PATH }}
